config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  post 'tweets/touser' => 'tweets#touser'
  root 'hello#index'
  
  # get 'tweets' => 'tweets#index'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id' => 'tweets#show' ,as: 'tweet'
  # patch 'tweets/:id' => 'tweets#update'
  # put 'tweets/:id' => 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'
  # get 'tweets/:id/edit' => 'tweets#edit', as:'edit_tweet'

  get 'tweets/scraping' => 'tweets#scraping'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :keeps, only: [:create, :destroy]
  end
  resources :rooms
  #get 'rooms' => 'rooms#index'
  resources :relationships, only: [:create, :destroy]
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    belongs_to :room, optional: true

    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :comments, dependent: :destroy
    has_many :keeps, dependent: :destroy
    has_many :kept_users, through: :keeps, source: :user
    
    #tweetsテーブルから中間テーブルに対する関連付け
    has_many :tweet_tag_relations, dependent: :destroy
    #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
    has_many :tags, through: :tweet_tag_relations, dependent: :destroy
    
    #動画投稿機能
    mount_uploader :video, VideoUploader
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    before_action :authenticate_user!

    def index
        require "date"
 
        @date = Date.today
        if params[:search] == nil
            @tweets= Tweet.all.page(params[:page]).per(8)
        elsif params[:search] == ''
            @tweets= Tweet.all.page(params[:page]).per(8)
        else
            #@tweets= Tweet.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(3)
            search = params[:search].to_s
            @tweets= Tweet.where("body LIKE ? ",'%' + search + '%').page(params[:page]).per(3)
        end

        #タグ検索実装
        @tagsearch = []
        if params[:tag_ids] == nil
            @tagId = [["選択されていません","1"]]
        else
            @tagId = params[:tag_ids]
        end

        if params[:tag_ids]
            @tagsearch = []
            params[:tag_ids].each do |key, value|      
                @tagsearch += Tag.find_by(name: key).tweets if value == "1"
            end
            @tagsearch.uniq!
        end

        #いいねランキング実装
        @all_ranks = Tweet.find(Like.group(:tweet_id).order('count(tweet_id) desc').limit(3).pluck(:tweet_id))

        #金額計算機能
        @total = params[:cut].to_f + params[:color].to_f + params[:perm].to_f + params[:radio].to_f

        #submitで切り替えできるか
        #@tweets = Tweet.where("body LIKE ? ",'%' + params[:tab] + '%')

        #URL取得
        @url = request.url
        #コントローラー名取得
        @controller = controller_name
        #@sample = @tweets.first(2..3)
        @sample = @tweets[3]
    end
    #userへ飛ばしたい！
    def touser
        tweet = Tweet.find(params[:tweet])
        user = tweet.user
        redirect_to  controller: :users, action: :show, id: user.id
    end

    #スクレイピング
    def scraping
        agent = Mechanize.new
        page = agent.get("https://radwimps.jp/")
        @elements = page.search('img')

        play = Mechanize.new
        page2 = play.get("https://hanshintigers.jp/data/player/2023/")
        @players = page2.search('dt>a')
    end

    def new
        @newtweet = Tweet.new

        
        rooms = [["roomを選択", 0]]
        Room.all.each do |r|
            room = []
            room.push(r.name)
            room.push(r.id)
            rooms.push(room)
        end
        @rooms = rooms
        @taggenre = Tag.select(:genre).distinct
    end


    def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id

        if tweet.save
            redirect_to  controller: :rooms, action: :show, id: tweet.room_id
        else
            redirect_to :action => "new"
        end
    end


    def show
        @tweet = Tweet.find(params[:id])
        @makky = "apple"
        @comments = @tweet.comments
        @comment = Comment.new


        tag_names = []
        @tweet.tags.each do |tag|
            tag_names.push(tag.name)
        end

        @tagsearch = []
        if tag_names
            tag_names.each do |tname|      
                @tagsearch += Tag.find_by(name: tname).tweets
            end
            @tagsearch.uniq!
        end
    end

    def edit
        @tweet = Tweet.find(params[:id])
        @tagsearch = []
    end

    def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
            redirect_to :action => "show", :id => tweet.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to :action => "index"
    end

    private
    def tweet_params
        params.require(:tweet).permit(:body, :image, :overall, :level, :room_id, :video, tag_ids: [])
    end

end

app/helpers/tweets_helper.rb
module TweetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
     
end

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> <br>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    <h5>総合評価</h5>
    <div class="post_form">
      <%= f.radio_button :overall, 5 ,id: 'star1'%>
      <label for="star1"><span class="text">最高</span>★</label>

      <%= f.radio_button :overall, 4 ,id: 'star2'%>
      <label for="star2"><span class="text">良い</span>★</label>

      <%= f.radio_button :overall, 3 ,id: 'star3'%>
      <label for="star3"><span class="text">普通</span>★</label>

      <%= f.radio_button :overall, 2 ,id: 'star4'%>
      <label for="star4"><span class="text">悪い</span>★</label>

      <%= f.radio_button :overall, 1 ,id: 'star5'%>
      <label for="star5"><span class="text">最悪</span>★</label>
    </div>
    <h5>授業レベル</h5>
    <%= f.number_field :level, max: "5", min: "1" %>
    </div>
    <%= f.submit "編集する" %>
<% end %>


app/views/tweets/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<iframe width="560" height="315" src="https://www.youtube.com/embed/TDi-hGRYX6g" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br>
<%= link_to "tweetする", new_tweet_path %>
<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% if user_signed_in? %>
  <%= link_to"マイページへ", user_path(current_user.id) %>
<% end %>
<%= link_to 'スクレイピング', tweets_scraping_path %>
<a href="/users/<%= current_user.id %>">mypage</a>
<%= link_to "rooms", rooms_path %>
<br>
<h4>ボタンで切り替えできるか？</h4>
<div class="tab">
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= hidden_field_tag :search, 'radwimps' %>
    <%= submit_tag 'radwimps' %>
<% end %>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= hidden_field_tag :search, 'テスト' %>
    <%= submit_tag 'テスト' %>
<% end %>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= hidden_field :search, 'vaundy' %>
    <%= submit_tag 'vaundy' %>
<% end %>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= submit_tag 'すべて' %>
<% end %>
</div>
<%= image_tag 'radwimps1.jfif', class: "img" %>
<%= @controller %>
<h3>日付：<%= @date %></h3>

<%= @url %>

<br>
<%= page_entries_info @tweets %>

<h2>Tweet一覧</h2>
<h3>投稿を検索</h3>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
  <%= text_field_tag :search %>
  <%= text_field_tag :search2 %>
  <%= submit_tag '検索する' %>
<% end %>


<div class="tweets-container">
  <% @tweets.each do |t| %>
  <% @num= @tweets.index(t) %>
  <%= @num %>
    <div class="tweet">
      <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
      <div class="ain-box">
        <div class="left-container">
          <%#<%= image_tag t.image_url, size: "250x200" if t.image? %>
          <%= link_to  tweet_path(t.id) do %>
            <%= image_tag t.image_url, size: "250x250" if t.image? %>
          <% end %><br>
          <%= form_tag({controller:"tweets",action:"touser"}, method: :post) do %>
            <%= hidden_field_tag :tweet, t.id %>
            <%= submit_tag '投稿者へ' %>
          <% end %>
          <%= t.body %>
          <div>
            <h5>総合評価：
              <span class="star-rating">
                <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
              </span>
            </h5>
          </div>
          <div>
            <h5>授業レベル：
              <span class="star-rating">
                <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
                <span class="star-rating-back">★★★★★</span>
              </span>
            </h5>
          </div>
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
          <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
          <% end %>
          <% t.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
        </div><!-- left-container -->

        <br>
        <div class="right-container">
          <%= link_to "詳細", tweet_path(t.id) %>
          <%= link_to "編集", edit_tweet_path(t.id) %>
          <%#= link_to "削除", tweet_path(t.id), method: :delete %>
          <a href="/tweets/<%= t.id %>"  data-method="delete"><i class="fa-solid fa-trash-can"></i></a>
        </div>
      </div> <!-- main-box -->
      <p class="time">
        <%= t.created_at.strftime('%Y/%m/%d') %><br>
        <%= t.created_at.to_s(:datetime_jp) %>
      </p>
    </div>
  <% end %>
  <%= paginate @tweets %>
</div>


<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索' %>
<% end %>

<% @tagId.each do |t| %>
  <% if t[1] == "1" %>
    <%= t[0] %>
  <% end %>
<% end %>

<% Tag.all.each do |t| %>    
  <% if t.id == :tag_ids %>
    <li><%= t.name %></li>  
  <% end %>
<% end %>
<% @i = 0 %>
<% @tagsearch.each do |t| %>
 <div class="tweet">
      <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
      <div class="main-box">
        <div class="left-container">
          <%= image_tag t.image_url, size: "250x200" if t.image? %><br>
          <%= t.body %>
          

          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% end %>
          <% else %>
            <p>いいねの数 = </p><%= t.likes.count %>
          <% end %>
          <p>tag</p>
          <% t.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
        </div>
        <div class="right-container">
          <%= link_to "詳細", tweet_path(t.id) %>
          <%= link_to "編集", edit_tweet_path(t.id) %>
          <%= link_to "削除", tweet_path(t.id), method: :delete %>
        </div>
      </div> <!-- main-box -->
      <p class="time">
        <%= t.created_at %>
      </p>
    </div>
<% end %>

<% @all_ranks.each do |rank| %>
  <%= rank.body %>
<% end %>


<br>
<br>


<h2>金額計算機能</h2>


<% if false %>
<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
  <%= check_box_tag :cut, 3000 %>
  <%= label_tag :cut, "カット" %>
  <%= check_box_tag :color, 6000 %>
  <%= label_tag :color, "カラー" %>
  <%= check_box_tag :perm, 9000 %>
  <%= label_tag :perm, "パーマ" %>
  <%= submit_tag '計算する' %>
<% end %>
<% end %>

<%= form_tag({controller:"tweets",action:"index"}, method: :get) do %>
    <%= number_field_tag :cut, '', step: "0.1" %>
    <%= number_field_tag :color, '', step: "0.1" %>
    <%= number_field_tag :perm, '', step: 0.1 %>

    <%= radio_button_tag("radio","10") %>
    <%= label_tag("radio_10","10")%>
    <%= radio_button_tag("radio","20") %>
    <%= label_tag("radio_20","20")%>
    <%= radio_button_tag("radio","30") %>
    <%= label_tag("radio_30","30")%>

    <%= submit_tag '計算する' %>
<% end %>
<%= @radio %>
<%= @total %>円


<br>
<br>
<br>
<br>

<%= @tagtag %>
<i class="fa-solid fa-location-dot"></i>

<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/jp/album/%E6%80%AA%E7%8D%A3%E3%81%AE%E8%8A%B1%E5%94%84/1?i=1510476618"></iframe>
<br>
<br>



<div class="オレンジ">
  <div class="Ⅰ.ピンク">
  </div>
  <div class="Ⅱ.ピンク">
    <div class="A.紫">
      <div class="1.青">
        <h2>2-1.HTML/CSSの概要</h2>
      </div>
      <div class="2.青">
        <div class="a)水色">
        </div>
        <div class="b)水色">
          <p class="(1)黄緑">
            2-1.・・・
          </p>
          <p class="(2)黄緑">
            2-2.・・・
          </p>
          <p class="(3)黄緑">
            2-3.・・・
          </p>
          <p class="(4)黄緑">
            2-4.・・・
          </p>
          <p class="(5)黄緑">
            2-5.・・・
          </p>
        </div>
      </div>
      <div class="3.青">
        <div class="a)水色">
        </div>
        <div class="b)水色">
        </div>
        <div class="c)水色">
        </div>
      </div>
    </div>
    <div class="B.紫">
      <div class="1.青">
      </div>
      <div class="2.青">
      </div>
    </div>
  </div>
</div>


<a class="twitter-timeline" data-width="500" data-height="300" data-theme="light" href="https://twitter.com/CrazyRaccoonCup?ref_src=twsrc%5Etfw">Tweets by CrazyRaccoonCup</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


app/views/tweets/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>


<div class="post-container">
  <p class="title">新規投稿</p>
  <%= form_for(@newtweet, :url => { controller:'tweets', action:'create'}) do |f| %>
    <%= f.label :投稿内容 %>
    <br>
    <%= f.text_field :body, :size => 140, class: "imput" %>
    <br>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %><br>
      <%= f.label :video %>
      <%= f.file_field :video %>
    </div>
    <div class='form-group'>
        <% @taggenre.each do |t| %>
              <p><b><%= t.genre%></b></p>
          <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <% if tag.object.genre == t.genre %>
              <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                  <%= tag.check_box class: 'form-check-input' %>
                  <%= tag.text %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <h5>総合評価</h5>
      <div class="post_form">
        <%= f.radio_button :overall, 5 ,id: 'star1'%>
        <label for="star1"><span class="text">最高</span>★</label>

        <%= f.radio_button :overall, 4 ,id: 'star2'%>
        <label for="star2"><span class="text">良い</span>★</label>

        <%= f.radio_button :overall, 3 ,id: 'star3'%>
        <label for="star3"><span class="text">普通</span>★</label>

        <%= f.radio_button :overall, 2 ,id: 'star4'%>
        <label for="star4"><span class="text">悪い</span>★</label>

        <%= f.radio_button :overall, 1 ,id: 'star5'%>
        <label for="star5"><span class="text">最悪</span>★</label>
      </div>
      <h5>授業レベル</h5>
      <%= f.number_field :level, max: "5", min: "1" %>
    </div>
    <%= f.submit "投稿する" %>
    room
    <%= f.select :room_id, @rooms %>
    <br>
  <% end %>
</div>


<%= link_to "Tweet一覧に戻る", tweets_path %>

<% @taggenre.each do |g| %>
  <%= g.genre %>
<% end %>

<br>
<br>




app/views/tweets/scraping.html.erb
<% @elements.each do |ele| %>
  <%#= ele %>
  <%#= image_tag ele[:src] %>
  <img src="<%= ele[:src]%>" width="275">
<% end %>

<br>
<% @players.each do |player| %>
  <%= player.inner_text %><br>
<% end %>

app/views/tweets/show.html.erb
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <%= image_tag @tweet.image_url, size: "250x250" if @tweet.image? %>
  <%= video_tag @tweet.video_url ,:controls => true if @tweet.video? %>
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at.to_s(:datetime_jp) %></p>
  <% if user_signed_in? %>
    <% if current_user.already_liked?(@tweet) %>
      <%= link_to tweet_like_path(@tweet), method: :delete do %>
        <i class="fas fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% else %>
      <%= link_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), method: :post do %>
        <i class="far fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% end %>
  <% else %>
    <p>いいねの数＝</p><%= @tweet.likes.count %>
  <% end %>
  <p>tag</p>
  <% @tweet.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>


<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      ・<%= c.user.email unless c.user.blank? %>:<%= c.content %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
       <i class="far fa-comments"></i>コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<p>保存機能</p>
<% if user_signed_in? %>
  <% if current_user.already_kept?(@tweet) %>
    <%= link_to tweet_keep_path(@tweet), method: :delete do %>
      <i class="fas fa-solid fa-bookmark"></i><br>
    <% end %>
  <% else %>
    <%= link_to tweet_keeps_path(@tweet), method: :post do %>
      <i class="far fa-solid fa-bookmark"></i><br>
    <% end %>
  <% end %>
<% end %>

<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

<%= link_to "Tweet一覧に戻る", tweets_path %>

<% @tagsearch.each do |t| %>
 <div class="tweet">
      <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
      <div class="main-box">
        <div class="left-container">
          <%= t.body %>
          <% t.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
        </div>
      </div> <!-- main-box -->
      <p class="time">
        <%= t.created_at %>
      </p>
    </div>
<% end %>

<br>
<br>
<br>