config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  post 'tweets/touser' => 'tweets#touser'
  root 'hello#index'
  
  # get 'tweets' => 'tweets#index'
  # get 'tweets/new' => 'tweets#new'
  # post 'tweets' => 'tweets#create'
  # get 'tweets/:id' => 'tweets#show' ,as: 'tweet'
  # patch 'tweets/:id' => 'tweets#update'
  # put 'tweets/:id' => 'tweets#update'
  # delete 'tweets/:id' => 'tweets#destroy'
  # get 'tweets/:id/edit' => 'tweets#edit', as:'edit_tweet'

  get 'tweets/scraping' => 'tweets#scraping'
  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :keeps, only: [:create, :destroy]
  end
  resources :rooms
  #get 'rooms' => 'rooms#index'
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/keep.rb
class Keep < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :tweets
  
  #tweetsを通してuserの所属してるroomsをとってくる
  has_many :users, through: :tweets

  has_many :joined_users, through: :tweets, source: :user

  def already_joining?(user)
    self.tweets.exists?(user_id: user.id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :tweet_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してTweetsテーブルへの関連付け
  has_many :tweets, through: :tweet_tag_relations, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord

    belongs_to :user
    belongs_to :room, optional: true

    mount_uploader :image, ImageUploader

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    has_many :comments, dependent: :destroy
    has_many :keeps, dependent: :destroy
    has_many :kept_users, through: :keeps, source: :user
    
    #tweetsテーブルから中間テーブルに対する関連付け
    has_many :tweet_tag_relations, dependent: :destroy
    #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
    has_many :tags, through: :tweet_tag_relations, dependent: :destroy
    
    #動画投稿機能
    mount_uploader :video, VideoUploader
end

app/models/tweet_tag_relation.rb
class TweetTagRelation < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  has_many :comments, dependent: :destroy

  has_many :keeps, dependent: :destroy
  has_many :kept_tweets, through: :keeps, source: :tweet
  
  def already_kept?(tweet)
    self.keeps.exists?(tweet_id: tweet.id)
  end

  # 所属Roomを表示
  has_many :rooms, through: :tweets

  has_many :joined_rooms, through: :tweets, source: :room

  def already_joined?(room)
    self.tweets.exists?(room_id: room.id)
  end

  #follow機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

    def index
    end

    def link
    end
    
end

app/controllers/keeps_controller.rb
class KeepsController < ApplicationController
    def create
        keep = current_user.keeps.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        keep = Keep.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        keep.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end

    def destroy
        like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!

    def index
        @rooms = Room.all
        @tweets = Tweet.all
    end

    def new
        @room = Room.new
    end

    def create
        room = Room.new(room_params)

        if room.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @room = Room.find(params[:id])
        @users = User.all
        
        #ranking実装
        @roomtweets = Room.find(params[:id]).tweets
        @ranks = User.find(@roomtweets.group(:user_id).order('count(id) desc').pluck(:user_id))
    end
  
    private
      def room_params
        params.require(:room).permit(:name)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(current_user.id)
        @user = User.find(params[:id])
        @tweets = @user.tweets.page(params[:page]).per(10)
        @userrooms = User.find(params[:id]).rooms
        @rooms = Room.all


        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
     
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/index.html.erb
<%= stylesheet_link_tag 'rooms', :media => "all" %>
<div class="rooms-container">
  <%= link_to "ルームを追加", new_room_path %>
  <br>
  <br>
  <h4>room一覧</h4>
  <% @rooms.each do |r| %>
    ・<%= link_to  room_path(r.id) do %><%= r.name %><% end %><br>
  <% end %>
</div>

<% @tweets.each do |r| %>
    ・<%= r.body %><br>
  <% end %>
  
<%= @hisato %>


app/views/rooms/new.html.erb
<%= form_for(@room, :url => { controller:'rooms', action:'create'}) do |f| %>
  <%= f.label :room %>
  <%= f.text_field :name, :size => 140, class: "imput" %>
  <%= f.submit %>
<% end %>

<%= link_to "rooms", rooms_path %>

app/views/rooms/show.html.erb
<%= stylesheet_link_tag 'roomshow', :media => "all" %>
<%= link_to "rooms一覧に戻る", rooms_path %>

<br>
<h4>room名：<%= @room.name %></h4>

<% @users.each do |u| %>
  <% if u.already_joined?(@room) %>
    <%= u.name %><br>
  <% end %>
<% end %>

<br>
<h4>メンバーの投稿</h4>
<% @room.tweets.each do |t| %>
  〇<%= t.body %>
  /<%= t.user.name %><br>
<% end %>



<br>
<h4>ranking</h4>
<% @ranks.each.with_index(1) do |u, i| %>
  第<%= i %>位：<%= u.name %>✨<br>
<% end %>

<br>
<h4>メンバーの投稿：チャット風</h4>
<% @room.tweets.each do |t| %>
  <% if user_signed_in? %>
    <% if t.user.id == current_user.id %>
      <div class="self-tweet room-tweet">
        <p>
          〇<%= t.body %>
          /自分<br>
        </p>
      </div>
    <% else %>
      <div class="room-tweet">
        <P>
          〇<%= t.body %>
          /<%= t.user.name %><br>
        </P>
      </div>
    <% end %>  
  <% else %>
    <div class="left-display">
      <p>
        〇<%= t.body %>
        /<%= t.user.name %><br>
      </p>
    </div>
  <% end %>
<% end %>

<br>
<br>
<br>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前：<%= @user.name %></p>
<p>メールアドレス：<%= @user.email %></p>
<i class="fab fa-solid fa-location-dot"></i>
プロフィール：<%= @user.profile %>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2><%= render 'relationships/follow_button', user: @user %></h2>

<h4>follower</h4>
<% @user.followers.each do |f| %>
  <p><%= f.name %></p>
<% end %>
<h4>following</h4>
<% @user.followings.each do |f| %>
  <p><%= f.name %></p>
<% end %>
<br>


<h2>あなたの投稿一覧</h2>
<% @tweets.each do |t| %>
  <p>〇<%= t.body %></p>
  <% t.comments.each do |c| %>
    <p>
      ・<%= c.user.email unless c.user.blank? %>:<%= c.content %>
    </p>
  <% end %>
<% end %>
<%= paginate @tweets %>

<br>
<%= link_to "Tweet一覧に戻る", tweets_path %>

<br>
<br>
<h4>コメントがついた投稿のみ表示</h4>
<% @user.tweets.each do |t| %>
  <% if t.comments.count != 0 %>
    <p>〇<%= t.body %></p>
    <% t.comments.each do |c| %>
      <p>
        ・<%= c.user.email unless c.user.blank? %>:<%= c.content %>
      </p>
    <% end %>
  <% end %>
<% end %>

<br>
<h4>コメントした投稿のみ表示</h4>
<% @user.comments.each do |c| %>
  <p>〇<%= c.tweet.body %></p>
  <p>・<%= c.content %></p>
<% end %>


<h4>所属room</h4>
<% @rooms.each do |r| %>
  <% if r.already_joining?(@user) %>
    <%= r.name %><br>
  <% end %>
<% end %>


<%# javascript %>
<%#<input type="hidden" id="sample" value="<%= @userrooms[0].name %>
<% if false %>
  <script>
    window.onload = function() {
      const sample = document.getElementById('sample').value
      console.log(sample);
    } 
      console.log("Hello world!");
      alert("20歳以上の方を対象にしたサイトです。20歳未満の方はご利用いただけません。");
  </script>
<% end %>

<br>
<br>